apiVersion: skaffold/v2beta8
kind: Config
deploy:
  kubectl:
    manifests:
      - "./k8s/*"
build:
  artifacts:
    - image: ait-cr.akarinti.tech/java-standard:1.0
      docker:
        dockerfile: Dockerfile
